version: 2
jobs:
  ponyup:
    docker:
      - image: ponylang/ponyc:latest
    steps:
      - checkout

      - run: apt-get update -y && apt-get install -y shellcheck
      - run: shellcheck ponyup-init.sh

      - run: .ci-scripts/install-openssl.sh

      - run: stable fetch && make
      - run: make test
      - run: .ci-scripts/remove-ponyc.sh
      - run: |
          export PATH=$(pwd)/.pony_test/ponyup/bin:$PATH
          make clean
          make

workflows:
  version: 2
  commit:
    jobs:
      - ponyup
  nightly:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only: master
    jobs:
      - ponyup
